### ISSUE TITLE
Browserless uncaught exception

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#104]
Node-RED stacktrace

```
auto-tilskudsberegning-fodterapi-node-red-1  | 7 Nov 09:40:41 - [red] Uncaught Exception:
auto-tilskudsberegning-fodterapi-node-red-1  | 7 Nov 09:40:41 - [error] ProtocolError: Protocol error (Input.dispatchMouseEvent): Target closed
auto-tilskudsberegning-fodterapi-node-red-1  |     at new Callback (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
auto-tilskudsberegning-fodterapi-node-red-1  |     at CallbackRegistry.create (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
auto-tilskudsberegning-fodterapi-node-red-1  |     at Connection._rawSend (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
auto-tilskudsberegning-fodterapi-node-red-1  |     at CDPSessionImpl.send (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
auto-tilskudsberegning-fodterapi-node-red-1  |     at /usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:496:69
auto-tilskudsberegning-fodterapi-node-red-1  |     at Mouse._Mouse_withTransaction (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:706:15)
auto-tilskudsberegning-fodterapi-node-red-1  |     at Mouse.down (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:491:91)
auto-tilskudsberegning-fodterapi-node-red-1  |     at Mouse.click (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:553:27)
auto-tilskudsberegning-fodterapi-node-red-1  |     at CDPElementHandle.click (/usr/src/node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js:275:112)
auto-tilskudsberegning-fodterapi-node-red-1  |     at runMicrotasks (<anonymous>)
```

**Comment by st-randers** [comment]
2023-11-07T10:18:58.437Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: /: Inbound WebSocket request.
2023-11-07T10:18:58.438Z browserless:hardware Checking overload status: CPU 5% Memory 26%
2023-11-07T10:18:58.439Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Adding new job to queue.
2023-11-07T10:18:58.439Z browserless:server Starting new job
2023-11-07T10:18:58.439Z browserless:system Generating fresh chrome browser
2023-11-07T10:18:58.439Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Getting browser.
2023-11-07T10:18:58.439Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--remote-debugging-port=45065",
    "--user-data-dir=/tmp/browserless-data-dir-RZ51MB",
    "--remote-debugging-pipe"
  ],
  "blockAds": false,
  "dumpio": false,
  "headless": true,
  "stealth": false,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "playwright": false,
  "userDataDir": "/tmp/browserless-data-dir-RZ51MB",
  "meta": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": {},
    "pathname": "/",
    "path": "/",
    "href": "/"
  },
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false,
  "handleSIGHUP": false
}
2023-11-07T10:18:58.505Z browserless:chrome-helper Chrome PID: 438
2023-11-07T10:18:58.506Z browserless:chrome-helper Finding prior pages
2023-11-07T10:18:58.531Z browserless:chrome-helper Found 1 pages
2023-11-07T10:18:58.531Z browserless:chrome-helper Setting up page Unknown
2023-11-07T10:18:58.531Z browserless:chrome-helper Patching file-chooser dialog
2023-11-07T10:18:58.531Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2023-11-07T10:18:58.531Z browserless:system Chrome launched 92ms
2023-11-07T10:18:58.531Z browserless:system Got chrome instance
2023-11-07T10:18:58.531Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Starting session.
2023-11-07T10:18:58.531Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Proxying request to /devtools/browser route: ws://127.0.0.1:45065/devtools/browser/4cd4ac0b-3e34-4660-8059-702c806ffbfe.
2023-11-07T10:18:58.533Z browserless:chrome-helper Setting up file:// protocol request rejection
2023-11-07T10:18:58.653Z browserless:chrome-helper Setting up page Unknown
2023-11-07T10:18:58.653Z browserless:chrome-helper Patching file-chooser dialog
2023-11-07T10:18:58.653Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2023-11-07T10:18:58.654Z browserless:chrome-helper Setting up file:// protocol request rejection
2023-11-07T10:19:18.650Z browserless:server 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Recording successful stat and cleaning up.
2023-11-07T10:19:18.650Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Cleaning up job
2023-11-07T10:19:18.650Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Browser not needed, closing
2023-11-07T10:19:18.650Z browserless:chrome-helper Shutting down browser with close command
2023-11-07T10:19:18.650Z browserless:job 8SVE84LU9CTH3YIFB96DG1KIRNK11TKD: Browser cleanup complete.
2023-11-07T10:19:18.650Z browserless:server Current workload complete.
2023-11-07T10:19:18.650Z browserless:chrome-helper Sending SIGKILL signal to browser process 438
2023-11-07T10:19:18.659Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-RZ51MB
2023-11-07T10:19:18.689Z browserless:chrome-helper Garbage collecting and removing listeners
2023-11-07T10:19:18.696Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-RZ51MB removed successfully

**Comment by st-randers** [comment]
Ny browserless stacktrace efter forsøg med diverse puppeteer launch args

```
2023-11-07T10:49:45.946Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: /?ignoreHTTPSErrors=true&exitOnPageError=false&keepalive=30000&--no-zygote&--disable-site-isolation-trials&--disable-dev-shm-usage&--disable-features=IsolateOrigins&--deterministic-fetch&--disable-setuid-sandbox&--disable-gpu&headless=true: Inbound WebSocket request.
2023-11-07T10:49:45.947Z browserless:hardware Checking overload status: CPU 6% Memory 27%
2023-11-07T10:49:45.948Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Adding new job to queue.
2023-11-07T10:49:45.948Z browserless:server Starting new job
2023-11-07T10:49:45.948Z browserless:system Generating fresh chrome browser
2023-11-07T10:49:45.948Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Getting browser.
2023-11-07T10:49:45.949Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--no-zygote",
    "--disable-site-isolation-trials",
    "--disable-dev-shm-usage",
    "--disable-features=IsolateOrigins",
    "--deterministic-fetch",
    "--disable-setuid-sandbox",
    "--disable-gpu",
    "--remote-debugging-port=38873",
    "--user-data-dir=/tmp/browserless-data-dir-A4jH5k",
    "--remote-debugging-pipe"
  ],
  "blockAds": false,
  "dumpio": false,
  "headless": true,
  "stealth": false,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": true,
  "keepalive": 30000,
  "pauseOnConnect": false,
  "playwright": false,
  "userDataDir": "/tmp/browserless-data-dir-A4jH5k",
  "meta": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": "?ignoreHTTPSErrors=true&exitOnPageError=false&keepalive=30000&--no-zygote&--disable-site-isolation-trials&--disable-dev-shm-usage&--disable-features=IsolateOrigins&--deterministic-fetch&--disable-setuid-sandbox&--disable-gpu&headless=true",
    "query": {
      "ignoreHTTPSErrors": "true",
      "exitOnPageError": "false",
      "keepalive": "30000",
      "--no-zygote": "",
      "--disable-site-isolation-trials": "",
      "--disable-dev-shm-usage": "",
      "--disable-features": "IsolateOrigins",
      "--deterministic-fetch": "",
      "--disable-setuid-sandbox": "",
      "--disable-gpu": "",
      "headless": "true"
    },
    "pathname": "/",
    "path": "/?ignoreHTTPSErrors=true&exitOnPageError=false&keepalive=30000&--no-zygote&--disable-site-isolation-trials&--disable-dev-shm-usage&--disable-features=IsolateOrigins&--deterministic-fetch&--disable-setuid-sandbox&--disable-gpu&headless=true",
    "href": "/?ignoreHTTPSErrors=true&exitOnPageError=false&keepalive=30000&--no-zygote&--disable-site-isolation-trials&--disable-dev-shm-usage&--disable-features=IsolateOrigins&--deterministic-fetch&--disable-setuid-sandbox&--disable-gpu&headless=true"
  },
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false,
  "handleSIGHUP": false
}
2023-11-07T10:49:45.998Z browserless:chrome-helper Chrome PID: 1720
2023-11-07T10:49:45.998Z browserless:chrome-helper Finding prior pages
2023-11-07T10:49:46.033Z browserless:chrome-helper Found 1 pages
2023-11-07T10:49:46.033Z browserless:chrome-helper Setting up page Unknown
2023-11-07T10:49:46.033Z browserless:chrome-helper Patching file-chooser dialog
2023-11-07T10:49:46.033Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2023-11-07T10:49:46.033Z browserless:system Chrome launched 85ms
2023-11-07T10:49:46.033Z browserless:system Got chrome instance
2023-11-07T10:49:46.033Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Starting session.
2023-11-07T10:49:46.033Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Proxying request to /devtools/browser route: ws://127.0.0.1:38873/devtools/browser/5b930878-d6f3-4cc5-9e58-90f8cb9f93b1.
2023-11-07T10:49:46.035Z browserless:chrome-helper Setting up file:// protocol request rejection
2023-11-07T10:49:46.174Z browserless:chrome-helper Setting up page Unknown
2023-11-07T10:49:46.174Z browserless:chrome-helper Patching file-chooser dialog
2023-11-07T10:49:46.174Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2023-11-07T10:49:46.174Z browserless:chrome-helper Setting up file:// protocol request rejection
2023-11-07T10:49:50.704Z browserless:job LS9SM6NXIXCBNTD1OQ7EGFZWLQINTKM5: /devtools/page/4535C9721F3AE03A4EB9D9257EAB57E9: Inbound WebSocket request.
2023-11-07T10:50:06.830Z browserless:server FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Recording successful stat and cleaning up.
2023-11-07T10:50:06.830Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Cleaning up job
2023-11-07T10:50:06.830Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Browser marked as keep-alive, closing in 30000ms
2023-11-07T10:50:06.830Z browserless:server Current workload complete.
2023-11-07T10:50:07.046Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:09.516Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:12.011Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:13.881Z browserless:job EQ21CM6AWWFG8KYAA9NFLROI5FQXKW91: /devtools/page/4535C9721F3AE03A4EB9D9257EAB57E9: Inbound WebSocket request.
2023-11-07T10:50:13.882Z browserless:system Error in WebSocket handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:15.048Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:17.026Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:20.041Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:22.062Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:25.054Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:27.052Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:29.515Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:32.044Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:35.044Z browserless:system Error in route handler: FetchError: request to http://127.0.0.1:38873/json/list failed, reason: connect ECONNREFUSED 127.0.0.1:38873
2023-11-07T10:50:36.830Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Browser not needed, closing
2023-11-07T10:50:36.830Z browserless:chrome-helper Shutting down browser with close command
2023-11-07T10:50:36.831Z browserless:job FHTVJY88I75A2Q2AGR91DN0MQ2Q7D0P6: Browser cleanup complete.
2023-11-07T10:50:36.831Z browserless:chrome-helper Sending SIGKILL signal to browser process 1720
2023-11-07T10:50:36.839Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-A4jH5k
2023-11-07T10:50:36.840Z browserless:chrome-helper Garbage collecting and removing listeners
2023-11-07T10:50:36.847Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-A4jH5k removed successfully
```

**Comment by st-randers** [comment]
Issue løst ved ændring af puppeteer click kode.
